SELECT *
FROM EMPLOYEE_PAY_TBL
WHERE SALARY>20000 AND POS IN ('SHIPPER', 'MARKETING');

SELECT *
FROM EMPLOYEE_PAY_TBL
WHERE SALARY BETWEEN 20000 AND 30000 AND POS IN ('SHIPPER', 'MARKETING');

SELECT *
FROM EMPLOYEE_PAY_TBL
WHERE SALARY NOT IN (20000, 30000, 40000) AND POS IN ('SHIPPER', 'MARKETING');