SELECT MAX(BONUS) AS MAX_BONUS
FROM EMPLOYEE_PAY_TBL;

SELECT MIN(PAY_RATE) AS MIN_SATNICA
FROM EMPLOYEE_PAY_TBL;

SELECT COUNT(*) AS SVI_ZAPOSLENI
FROM EMPLOYEE_PAY_TBL;

SELECT COUNT(*) AS BR_ZAPOSLENIH
FROM EMPLOYEE_TBL
WHERE LAST_NAME LIKE 'G%';