CREATE VIEW CUSTOMERS_PERSONS AS
SELECT LEFT(CUST_NAME, INSTR(CUST_NAME, ' ') - 1) AS CUST_FIRST_NAME, 
RIGHT(CUST_NAME, LENGTH(CUST_NAME) - INSTR(CUST_NAME, ' ') ) AS CUST_LAST_NAME, CUST_ADDRESS, CUST_CITY
FROM CUSTOMER_TBL
WHERE CUST_GENDER IS NOT NULL