CREATE VIEW PERSONS AS
SELECT LAST_NAME, FIRST_NAME, 'EMPLYEE' AS STATUS
FROM EMPLOYEE_TBL

UNION

SELECT CUST_LAST_NAME, CUST_FIRST_NAME, 'CUSTOMERS' AS STATUS
FROM CUSTOMERS_PERSONS

ORDER BY LAST_NAME DESC