SELECT CITY, ROUND(AVG(SALARY), 0) AS PROS_ZARADA 
FROM EMPLOYEE_TBL INNER JOIN SALARIES 
ON EMPLOYEE_TBL.EMP_ID = SALARIES.EMP_ID
GROUP BY CITY;

SELECT CITY, ROUND( AVG(TOTAL), 0) AS PROS_TOTAL
FROM EMPLOYEE_TBL INNER JOIN SALARIES
ON EMPLOYEE_TBL.EMP_ID = SALARIES.EMP_ID
GROUP BY CITY;