SELECT EMP_ID, DATE_HITE, YEAR(DATE_HITE) AS YEAR_HIRE, DAYNAME(DATE_HITE) AS DAY_HIRE, 
FLOOR(DATEDIFF(DATE(NOW()), DATE_HITE)/365.25) AS EMP_YEARS
FROM EMPLOYEE_PAY_TBL
WHERE DATE_HITE > '1990-12-31'