SELECT PROD_ID, SUM(QTY) AS UK_PRODATO
FROM ORDERS_TBL
GROUP BY PROD_ID;

SELECT PROD_ID, SUM(QTY) AS UK_PRODATO
FROM ORDERS_TBL
WHERE CUST_ID NOT IN ('43')
GROUP BY PROD_ID;

SELECT PROD_ID, SUM(QTY) AS UK_PRODATO
FROM ORDERS_TBL
WHERE CUST_ID NOT IN ('43')
GROUP BY PROD_ID
HAVING UK_PRODATO > 10
ORDER BY UK_PRODATO DESC;