SELECT POS, AVG(PAY_RATE) AS PROS_SATNICA, AVG(SALARY) AS PROS_PLATA
FROM EMPLOYEE_PAY_TBL
GROUP BY POS;

SELECT POS, AVG(PAY_RATE) AS PROS_SATNICA, AVG(SALARY) AS PROS_PLATA
FROM EMPLOYEE_PAY_TBL
WHERE POS NOT IN ('SALES MANAGER', 'TEAM LEADER')
GROUP BY POS;

SELECT POS, AVG(PAY_RATE) AS PROS_SATNICA, AVG(SALARY) AS PROS_PLATA
FROM EMPLOYEE_PAY_TBL
WHERE POS NOT IN ('SALES MANAGER', 'TEAM LEADER')
GROUP BY POS
HAVING PROS_PLATA > 30000
ORDER BY PROS_PLATA DESC;