CREATE TABLE CUSTOMER_TBL
(
CUST_ID	VARCHAR(10)	NOT NULL,
CUST_NAME	VARCHAR(20) NOT NULL,
CUST_ADDRESS	VARCHAR(30) NOT NULL,
CUST_CITY	VARCHAR(20) NOT NULL,
CUST_STATE	CHAR(2) NOT NULL,
CUST_ZIP	INT(5) NOT NULL,
CUST_COMPANY	VARCHAR(20)
);